ekf_filter_node:
  frequency: 50.0
  sensor_timeout: 0.1
  two_d_mode: true

  odom0: /wheel_odom  # Use raw odometry
  odom0_config: [true, true, false, false, false, true,  # x, y, yaw
                 false, false, false, false, false, false]  # velocities

  imu0: /imu/data  # Use IMU
  imu0_config: [false, false, false,  # x, y, z
                false, false, true,   # roll, pitch, yaw
                false, false, true,   # vx, vy, vz
                false, false, false]  # vroll, vpitch, vyaw

  imu0_differential: true
  imu0_queue_size: 10